fix(radioInput): Fix type of generic props
Hipo/react-ui-toolkit pull request #122
Opened 2021-07-07 08:15 UTC by mfarukkoc

### Description

- Added generic type with default type to functional component
- Removed default generic type from prop interface
- Updated type definitions on 'index.ts'

Closes #57

2021-07-09 11:01 UTC, edizcelik requested changes

2021-07-12 09:06 UTC, mfarukkoc commented on src/form/input/radio/RadioInput.tsx
> +export interface RadioInputItem<Id, Context> {
Default types were defined in the  `index.ts`. 

```index.ts 
export type RadioInputItem<Id = string, Context = any> = RadioInputComponentItem<
  Id,
  Context
>; 
```

I'm adding these defaults on `RadioInput.tsx` for other use cases too.

2021-07-12 10:28 UTC, edizcelik commented on src/form/input/radio/RadioInput.tsx
> +export interface RadioInputItem<Id, Context> {
The real definition of `RadioInputItem` is made here, so its always better to define the defaults here too. Even though the users of the toolkit does not import this definition directly (they import the alias created on index.tsx), this improves the developer experience.

2021-07-12 10:29 UTC, edizcelik approved these changes

2021-07-13 10:42 UTC, mucahit approved these changes

2021-07-13 11:27 UTC, merged