feat(components): Add PasswordInput component
Hipo/react-ui-toolkit pull request #34
Opened 2020-10-08 11:05 UTC by burakguneli

2020-10-09 06:51 UTC, jamcry commented on src/form/password-input/PasswordInput.tsx
> +  const passwrodInputIconClassName = classNames("password-input__icon", {
```suggestion
  const passwordInputIconClassName = classNames("password-input__icon", {
```
There is a small typo here

2020-10-09 06:51 UTC, jamcry commented on src/form/password-input/PasswordInput.tsx
> +  passwordVisibilityButtonTestId
I think this we can generate this inside the component using `testid`, and remove this prop
```
passwordVisibilityButtonTestId = `${testid}-password-visibility-icon`;
```

2020-10-09 06:51 UTC, jamcry commented on src/form/password-input/_password-input.scss
> +  }
I guess we don't need to nest this

2020-10-09 09:00 UTC, mucahit requested changes
Thanks! @burakguneli 

Here are a few minor requests

2020-10-09 09:00 UTC, mucahit commented on src/form/password-input/PasswordInput.tsx
> +  hidePasswordButtonIcon?: Node;
```suggestion
  hideIcon?: React.ReactNode;
  revealIcon?: React.ReactNode
```

2020-10-09 09:00 UTC, mucahit commented on src/form/password-input/PasswordInput.tsx
> +  testid: string;
```suggestion
  testid?: string;
```

2020-10-09 09:00 UTC, mucahit commented on src/form/password-input/_password-input.scss
> +  .password-input__icon--is-visible {
```suggestion
  &__icon--is-visible {
```

2020-10-09 09:00 UTC, mucahit commented on src/form/password-input/PasswordInput.tsx
> +export interface PasswordInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
How is this one?

```suggestion
export interface PasswordInputProps extends Omit<InputProps, "leftIcon" | "rightIcon"> {
  hideIcon?: React.ReactNode;
  revealIcon?: React.ReactNode
}
```

2020-10-09 09:11 UTC, bilgeyucel approved these changes

2020-10-15 08:22 UTC, edizcelik approved these changes

2020-10-21 07:29 UTC, jamcry approved these changes

2020-10-26 09:37 UTC, mucahit commented on src/form/password-input/PasswordInput.tsx
> +export interface PasswordInputProps extends Omit<InputProps, "leftIcon" | "rightIcon"> {
Let's convert to this, as far as I can see you're not overriding `InputProps` in here 

```suggestion
export interface PasswordInputProps extends Omit<InputProps, "leftIcon" | "rightIcon"> {
  hideIcon?: React.ReactNode;
  revealIcon?: React.ReactNode;
}
```

2020-11-03 11:41 UTC, mucahit approved these changes

2020-11-05 11:36 UTC, merged