feat(dropdown): Add samples with icon/subtitle/context/menu
Hipo/react-ui-toolkit pull request #65
Opened 2021-04-08 15:16 UTC by yasincaliskan

### Description
- Dropdown subtitle CSS class has `font-size` properties smaller than the title class.
- Dropdown samples have separated as `States`, `No Options`, `Pending Request`, `Disabled`.

### New Samples
- Dropdown Menu with icon
- Dropdown options with subtitle
- Dropdown with customized options

### Related Issue
- https://github.com/Hipo/react-ui-toolkit/issues/50

2021-04-09 12:47 UTC, edizcelik requested changes

2021-04-09 12:47 UTC, edizcelik commented on stories/1-Dropdown.stories.tsx
> +    <StateProvider initialState={initialStateWithContext}>
This doesn't show how one would use "Customized Options" but shows the use of `context`

2021-04-09 12:47 UTC, edizcelik commented on stories/1-Dropdown.stories.tsx
> +const initialState = {
Let's define the types for these variables. Also lets try to move them to a separate module, e.g. `dropdownStoryConstants`

2021-04-09 12:47 UTC, edizcelik commented on stories/1-Dropdown.stories.tsx
> +                    </style>
There should be a better way of doing this

2021-04-13 09:14 UTC, bilgeyucel approved these changes
I really liked the examples you provided. Seems neat, thanks 💯

2021-04-13 13:51 UTC, yasincaliskan commented
Thank you so much! 🎉

2021-04-14 09:51 UTC, jamcry approved these changes

2021-04-14 10:00 UTC, Anlerkan approved these changes

2021-04-14 10:16 UTC, mucahit approved these changes

2021-04-15 08:14 UTC, edizcelik approved these changes

2021-04-15 12:38 UTC, merged